### PR TITLE
Hypotheses test for variance and difference of means (known or unknoen variances, large or small samples size)

### PR DESCRIPTION
**Pull request by marcosmarva**
Hypotheses test for 
      * variance 
      * difference of means cosidering known or unknown variances, large or small sample size and, in the later case, sambles with equal or different variances.

### CODE REVIEW

**Comment by PostDataStatistics** [comment]
@marcosmarva 
What about a summary of the changes, e.g. a list of new files added to the repo? Thanks.

**Comment by PostDataStatistics** [comment]
@marcosmarva,  please check if these are all the new files
 + 060401.Rnw
 + 060402.Rnw
 + 060403.Rnw
 + 060601.Rnw
 + 060602.Rnw
 + 06060201.Rnw
 + 06060202.Rnw
 + 06060203.Rnw
 + 060603.Rnw
 + 06060301.Rnw
 + 06060302.Rnw
 + 06060303.Rnw
 + 06060401.Rnw
 + 06060402.Rnw
 + 06060403.Rnw
 + 060701.Rnw
 + 060702.Rnw
 + 060703.Rnw
 + 060801.Rnw
 + 060802.Rnw
 + 060803.Rnw

**Comment by marcosmarva** [comment]
Indeed, these are all the files

 Hypothesis test for sample variance, X ~ N(0,1), sample size n>30 

    * 060401.Rnw
    * 060402.Rnw
    * 060403.Rnw

 Hypothesis test for difference of Means, assumming known variances, sample sizes n1>30 and n2>30

    * 060601.Rnw
    * 060602.Rnw
    * 060603.Rnw

Hypothesis test for sample means difference, assuming unknown variances, X1 ~ N(0,1), X2 ~ N(0,1) sample sizes n1>30 n2>30

    * 06060201.Rnw
    * 06060202.Rnw
    * 06060203.Rnw

Hypothesis test for sample means difference, X1 ~ N(0,1), X2~ N(0,1) sample size n1<30, n2<30, unknown sigma1, sigma2 but assume sigma1=sigma2 

    * 06060301.Rnw
    * 06060302.Rnw
    * 06060303.Rnw

 Hypothesis test for sample means difference, X1 ~ N(0,1), X2 ~ N(0,1),  sample size n<30, unknown sigma1, sigma2 and assume sigma1 <> sigma2 

    * 06060401.Rnw
    * 06060402.Rnw
    * 06060403.Rnw

Hypothesis test for sample proportions difference (two populations) sample size n1>30, n2>30 

    * 060701.Rnw
    * 060702.Rnw
    * 060703.Rnw


Hypothesis test for sample variances (two populations), X1 and X2 normal variables

    * 060801.Rnw
    * 060802.Rnw
    * 060803.Rnw

**Comment by PostDataStatistics** [comment]
@marcosmarva Just merged, remember to sync local.

**Comment by marcosmarva** [comment]
I miss a kind of thesaurus, don't you?

**Comment by PostDataStatistics** [comment]
Yep, we''ll have to think of a way of making that info available. Maybe using the gh-pages for this repo.

**Pull request merged**
